name: analysis3
channels:
- conda-forge
- accessnri
- nodefaults
dependencies:
# SPEC0 packages
- cartopy
- cdo
- dask
- distributed
- hdf5
- ipython
- iris
- jupyter
- libnetcdf=*=mpi_openmpi*
- netcdf4
- notebook
- numpy
- pandas
- pip
- pygrib
- pyhdf
- pytest
- python>=3.11
- scipy
- seaborn
- sqlalchemy
- xarray
# Remaining packages
- accessnri::benchcab
- accessnri::access-nri-intake==1.0.0
- aiohttp
- aiohttp-cors
- anytree
- ants
- argopy
- arm_pyart
- arch-py
- asyncssh
- autopep8
- bargeparse
- black
- bokeh
- bottleneck
- branca
- celluloid
- cf-python
- cf-units
- cftime
- cfunits
- cfgrib
- climpred
- cmdline_provenance
- cmor
- cmocean
- compliance-checker
- conda-build
- conda-tree
- conda-verify
- crick ### Unlisted dependency for dask-expr
- cupy
- cvxpy
- dataclasses-json
- dataset
- datashader
- descartes
- dask-jobqueue
- dask-labextension
- dask-ml
- dask-xgboost
- dreqpy
- doc8
- docrep
- earthpy
- eccodes
- ecmwf-api-client
- eofs
- erddapy
- esmf=*=mpi_openmpi*
- esmpy
- f90nml
- ffmpeg
- filelock
- fiona
- flox
- folium
- fortran-language-server
- fs
- gcm_filters
- gcc_linux-64
- geocat-comp
- geocat-viz
- geopy
- geoplot
- gifsicle
- git
- greenlet ### Dependency of... something?
- gridfill
- gsw
- h5netcdf
- h5py
- hdbscan
- hdf5=1.14.4=mpi_openmpi*
- holoviews
- hupper
- hvplot
- icclim
- intake
- ipdb
- ipywidgets
- ipympl
- ipynbname
- iris-grib
- jags
- joblib
- jq
- jupyter-book
- jupyter-resource-usage
- jupyter-server-proxy
- jupyterlab
- jupyterlab_server
- kealib
- kerchunk
- lftp
- libgdal
- libnetcdf=*=mpi_openmpi*
- libtiff
- line_profiler
- lmfit
- mamba
- matchpy
- matplotlib
- matplotlib-scalebar
- matplotlib-venn
- mayavi
- memory_profiler
- metpy
- mo_pack
- mpl-scatter-density
- mplleaflet
- mopper
- mscorefonts
- nbdime
- nc-time-axis
- ncdu
- nctoolkit
- neutralocean
- ninja
- nodejs
- noise # unlisted dependency of xarray-spatial
- notebook
- nose
- numba
- numexpr>2.9
- numpy
- numpy_groupies
- objgraph ### Unlisted dependency of greenlet
- odc-geo
- openmpi==4.1.6
- opencv
- pandas
- panel
- parcels
- param
- pdbufr
- pint
- pip
- plotly
- poppler
- posix_ipc
- psutil
- pysal
- pytest-cov
- python>=3.11
- python-cdo
- python-eccodes
- python-gist
- python-graphviz
- python-kaleido
- python-magic
- python-stratify
- pytables
- pydap
- pyextremes
- pygrib
- pygam
- pyhdf
- pylint
- pymannkendall
- pyqt
- pytest
- rasterio
- rasterstats
- rechunker
- regionmask
- regional-mom6
- rioxarray
- s3fs
- satpy
- scikit-learn
- scipy
- seaborn
- sharppy
- sh
- shellcheck
- siphon
- spyder-kernels
- sqlalchemy
- statsmodels
- sympy
- tensorflow
- tintx
- timezonefinder
- twine
- tqdm
- u8darts-all
- ujson
- vtk
- watermark
- wavespectra
- watchdog
- webcolors
- windspharm
- wradlib
- wrf-python
- xarray
- xarray-spatial
- xarraymannkendall
- xcdat
- xclim
- xesmf
- xgcm
- xhistogram
- xmitgcm
- xmip
- xmovie
- xskillscore
- xrft
- xskillscore
- xwrf
- zarr
- pip:
  - git+https://github.com/intake/intake-esm.git
  - railroad-diagrams
