name: analysis3
channels:
  - accessnri
  - conda-forge
  - nodefaults
dependencies:
  - python==3.11.*
  - dask==2025.9.*
  - numpy==1.26.*
  - scipy==1.16.*
  - matplotlib>=3.9.*
  - pandas==2.3.*
  - scikit-image==0.25.*
  - scikit-learn==1.7.*
  - xarray==2025.10.1
  - ipython<9.0 # See ESMValTool
  - zarr>=3.1.0
  - iris==3.12.*
  - netcdf4==1.7.*
  - libnetcdf=*=mpi_openmpi*
  - openmpi==4.1.6
  - pip=25.*
  - hdf5=1.14.*=mpi_openmpi* # issues with version 1.14.3, version 1.14.4 not available for openmpi < 5.0
  - jupyterlab==4.3.2
  - cmor==3.9.*
  - accessnri::access-nri-intake==1.4.1
  - accessnri::intake-esm-access==2025.9.18
  - accessnri::ecgtools-access>=2025.10.7
  - accessnri::access-py-telemetry==0.1.9
  - accessnri::access-intake-utils==0.1.7
  - conda-forge::intake-dataframe-catalog==0.4.0
  - accessnri::yamanifest>=0.3.12
  - accessnri::access-med-tools==0.1.23
  - accessnri::access-mopper==2.3.0a24
  - accessnri::mule
  - accessnri::um-packing
  - accessnri::mule-utils
  - accessnri::mule-base
  - accessnri::um-spiral-search
  - accessnri::um-ppibm
  - accessnri::shumlib
  - aiohttp
  - aiohttp-cors
  - anytree
  - arch-py
  - argopy
  - arm_pyart
  - astropy
  - asyncssh
  - autopep8
  - av
  - bargeparse
  - black
  - bokeh
  - bottleneck
  - branca
  - cartopy
  - cdo
  - celluloid
  - cf-python
  - cf-units
  - cfchecker
  - cfgrib
  - cftime
  - cfunits
  - climpred
  - cmcrameri
  - cmdline_provenance
  - cmocean
  - cmor
  - compliance-checker
  - conda-build
  - conda-lock
  - conda-tree
  - conda-verify
  - crick
  - cupy
  - cvxpy
  - dask-jobqueue
  - dask-labextension
  - dask-ml
  - dask-xgboost
  - dataclasses-json
  - dataset
  - datashader
  - descartes
  - distributed
  - doc8
  - docrep
  - dreqpy
  - earthpy
  - eccodes
  - ecmwf-api-client
  - eofs
  - erddapy
  - esmf
  - esmpy
  - esmvalcore==2.13.*
  - f90nml
  - ffmpeg
  - filelock
  - fiona
  - flox
  - folium
  - fortran-language-server
  - fs
  - gcc_linux-64
  - gcm_filters
  - geocat-comp
  - geocat-viz
  - geoplot
  - geopy
  - gridfill
  - gsw
  - h5py
  - hdbscan
  - holoviews
  - httpx
  - hupper
  - hvplot
  - icclim
  - ilamb==2.7.2
  - intake
  - ipdb
  - ipympl
  - ipynbname
  - ipywidgets
  - iris-grib
  - jags
  - jinja2
  - joblib
  - jq
  - jsonschema>=4.18.1
  - jupyter
  - jupyter-book
  - jupyter-resource-usage
  - jupyter-server-proxy
  - jupyterlab_server
  - kerchunk
  - lftp
  - libgdal
  - libtiff
  - line_profiler
  - lmfit
  - mamba
  - matchpy
  - matplotlib-scalebar
  - matplotlib-venn
  - mayavi
  - memory_profiler
  - metpy
  - mo_pack
  - moderngl
  - mpi4py
  - mpl-scatter-density
  - mplleaflet
  - mscorefonts
  - nbdime
  - nb_conda_kernels
  - nc-time-axis
  - ncdata
  - ncdu
  - nctoolkit
  - neutralocean
  - ninja
  - nodejs
  - notebook==7.3.0
  - numba
  - numexpr
  - odc-geo
  - opencv
  - palettable
  - panel
  - papermill
  - param
  - parcels
  - pdbufr
  - pillow
  - pint
  - plotly
  - polars==1.32.0
  - poppler
  - posix_ipc
  - psutil
  - pyaml
  - pyarrow
  - pydantic
  - pydap
  - pyextremes
  - pygam
  - pygamma_n
  - pygrib
  - pygmt
  - pyhdf
  - pylint
  - pymannkendall
  - pysal
  - pyshp
  - pysteps
  - pytables
  - pytest
  - pytest-cov
  - pytest-subtests
  - python-eccodes
  - python-graphviz
  - python-magic
  - python-stratify
  - rasterio
  - rasterstats
  - rechunker
  - regional-mom6>=1.0.0
  - regionmask
  - rioxarray
  - ruff
  - s3fs
  - satpy
  - scores
  - seaborn
  - sh
  - sharppy
  - shellcheck
  - siphon
  - spyder-kernels
  - sqlalchemy
  - statsmodels
  - sympy
  - tensorflow
  - timezonefinder
  - tintx
  - tqdm
  - twine
  - u8darts-all
  - accessnri::ucx-py
  - ucx==1.15.0
  - ultraplot
  - ujson
  - vtk
  - watchdog
  - watermark
  - wavespectra
  - webcolors
  - windspharm
  - wradlib
  - wrf-python
  - xarray-spatial
  - xarraymannkendall
  - xcdat
  - xclim
  - xesmf
  - xgcm
  - xhistogram
  - xmip
  - xmitgcm
  - xmovie
  - xrft
  - xskillscore
  - xwrf

  - pip:
    - lavavu==1.9.10
    - lavavu-osmesa==1.9.10
    - railroad-diagrams ### Unlisted dependency of pip and pyparsing 
    - accessvis==1.1.4
    - py360convert
    - numpy-quaternion
    - pycnv

# Needed for ESMValTool merge
  - esmvaltool==2.13.*
  - cdsapi
  - curl<8.10
  - importlib_metadata<8 # https://github.com/ESMValGroup/ESMValTool/issues/3699 only for Python 3.10/11 and esmpy<8.6
  - lime
  - mapgenerator>=1.0.5
  - natsort
  - openpyxl
  - psyplot>=1.5.0
  - psy-maps>=1.5.0
  - psy-reg>=1.5.0
  - psy-simple>=1.5.0
  - pys2index
  - python-cdo
  - seawater
  - flake8
  - pytest-env
  - pytest-html
  - pytest-metadata
  - pytest-mock
  - pytest-xdist

# For documentation
  - autodocsumm>=0.2.2
  - nbsphinx
  - pydata-sphinx-theme
  - codespell==2.3.0
  - docformatter==1.7.5
  - imagehash
  - isort==5.13.2
  - pre-commit
  - prospector>=1.12
  - pyroma
  - yamllint==1.35.1
  - yapf
# NCL and dependencies
  - ncl
  - imagemagick
  - nco

# R and dependencies
  - cdo
  - r-base>=3.5,<4.3.0 # https://github.com/ESMValGroup/ESMValTool/pull/3924
  - r-abind
  - r-akima
  - r-climdex.pcic
  - r-climprojdiags
  - r-docopt
  - r-dotcall64
  - r-functional
  - r-ggplot2
  - r-gridextra
  - r-logging
  - r-mapproj
  - r-maps
  - r-multiapply
  - r-ncdf4
  - r-ncdf4.helpers
  - r-pcict
  - r-plyr
  - r-rcolorbrewer
  - r-rcpp
  - r-s2dverification
  - r-snow
  - r-spei
  - r-udunits2
  - r-yaml
# R packages needed for development
  - r-git2r # dependency of lintr
  - r-lintr==3.1.2
  - r-styler==1.10.3
