name: analysis3
channels:
- coecms
- conda-forge
- accessnri
- nodefaults
variables:
  CARTOPY_USER_BACKGROUNDS: /g/data/xp65/public/apps/cartopy-data/backgrounds
dependencies:
- python>=3.11
- pip
- sqlalchemy
- libnetcdf=*=mpi_openmpi*
- cdo
- hdf5
- cartopy
- dask
- distributed
- ipython
- iris
- netcdf4
- numpy
- pandas
- pygrib
- pyhdf
- pytest
- scipy
- seaborn
- xarray
- jupyter
- notebook
- metpy
- windspharm
- python-cdo
- arm_pyart
- bokeh
- datashader
- f90nml
- wrf-python
- sympy
- sh
- ffmpeg
- pydap
- twine
- python-graphviz
- joblib
- tqdm
- compliance-checker
- dataset
- xerces-c
- plotly
- zarr
- pytables
- nose
- ncdu
- cftime
- cfunits
- memory_profiler
- fs
- python-magic
- click_default_group
- regionmask
- rasterio
- gdal
- libgdal
- matplotlib
- dreqpy
- pint
- pycodestyle 
- nc-time-axis
- jq
- pvlib-python
- parcels
- siphon
- scikit-learn
- filelock
- gsw
- poppler
- fiona
- hupper
- kealib
- mo_pack
- mule
- cf-units
- python-stratify
- nbdime
- eofs
- eccodes
- python-eccodes
- h5py
- line_profiler
- bottleneck
- jupyterlab
- dask-jobqueue
- jupyterlab_server
- docrep
- gifsicle
- nodejs
- cfgrib
- h5netcdf
- intake
- gridfill
- xgcm
- xrft
- pylint
- matplotlib-venn
- nccmp
- cmocean
- marineHeatWaves
- holoviews
- geoviews
- pytest-cov
- panel
- xrft
- git
- openmpi==4.1.6
- mpi4py
- palettable
- xlrd
- nccompress
- mdssdiff
- mnctools
- satpy
- statsmodels
- dask-labextension
- nbstripout
- jupyter-server-proxy
- sphinx
- doc8
- climtas
- asyncssh
- ants
- xhistogram
- geopy
- ninja
- hvplot
- cython
- esmf=*=mpi_openmpi*
- esmpy
- xesmf
- sharppy
- docrep
- earthpy
- descartes
- era5grib
- conda-tree
- xmitgcm
- cupy
- rioxarray
- rasterstats
- windrose
- pyam
- pyarrow
- python-gist
- celluloid
- jags
- xarray-spatial
- noise # unlisted dependency of xarray-spatial
- nctoolkit
- geoplot
- dask-ml
- mamba
- pykrige
- nci_intake_catalogue
- cmdline_provenance
- mplleaflet
- branca
- fiona
- folium
- black
- aiohttp
- aiohttp-cors
- autopep8
- spyder-kernels
- dask-xgboost
- git-subtree
- xarray-spatial
- watermark
- cvxpy
- rechunker
- xmovie
- pymannkendall
- param
- tensorflow
- shap
- gh
- pyqt
- vtk
- mayavi
- gcm_filters
- timezonefinder
- lftp
- xarraymannkendall
- watchdog  
- numpy_groupies
- anytree
- fortran-language-server
- hdbscan
- jupyter-book
- iris-grib
- s3fs
- kerchunk
- ujson
- cafaz
- pygam
- pysal
- argopy
- dataclasses-json
- posix_ipc
- spectrum
- arch-py
- pyextremes
- ipdb
- palettable
- webcolors
- mpl-scatter-density
- accessnri::benchcab
- lmfit
- xclim
- jupyter-resource-usage
- matchpy
- mscorefonts
- opencv  
- conda-build
- conda-verify
- pygmt
- gmt
- greenlet ### Dependency of... something?
- objgraph ### Unlisted dependency of greenlet
- xarrayutils
- wradlib
- pyinterp
- wavespectra
- xmip
- xcdat
- neutralocean
- ipympl
- libtiff
- xskillscore
- geocat-comp
- ecgtools
- gcc_linux-64
- ipywidgets
- flox
- erddapy
- tintx
- climpred
- odc-geo
- cmor
- bargeparse
- accessnri::amami
- accessnri::access-nri-intake==1.0.0
- ipynbname
- shellcheck
- pysteps
- ucx-py
- ucx==1.15.0
- geocat-viz
- icclim
- py-cordex
- pdbufr
- matplotlib-scalebar
- python-kaleido
- numba
- crick ### Unlisted dependency for dask-expr
- regional-mom6
- u8darts-all
- xwrf
- ecmwf-api-client
- pygamma_n
- numexpr>2.9
- mopper
- scores
- cf-python
- esmvalcore==2.11.*
- pip:
  - git+https://github.com/intake/intake-esm.git
  - railroad-diagrams ### Unlisted dependency of pip and pyparsing
