[workspace]
authors = ["Charles Turner <charles.turner@anu.edu.au>"]
channels = ["accessnri", "conda-forge", "nodefaults", "rapidsai", "pytorch", "nvidia"]
name = "analysis3"
platforms = ["linux-64"]
version = "0.1.0"

[environments]
analysis3 = ["default"]

[tasks]
ensure-locked = { cmd = "pixi lock --check", description = "Ensure the lockfile is up to date" }
export-json = { cmd = "pixi list --json > solved.json", description = "Export the solved environment to JSON format" , depends-on = ["ensure-locked"] }
create-backup-env = {cmd = "mv environment.yml environment.yml.bak", description = "Create a backup of the current environment.yml file", depends-on = ["export-json"] }
rebuild-env = { cmd = "bash recreate-env-yml.sh", description = "Rebuild environment.yml from solved.json", depends-on = ["create-backup-env"] }

[dependencies]
python = "3.12.*"
dask = "2026.1.*"
numpy = ">2.0"
scipy = "1.17.*"
matplotlib = ">=3.10"
pandas = "2.3.*"
scikit-image = "0.26.*"
scikit-learn = "1.8.*"
xarray = "==2026.1.0"
ipython = "*"
zarr = ">=3.1.0"
iris = "3.14.*"
netcdf4 = "1.7.*"
libnetcdf = { version = "*", build = "mpi_openmpi*" }
openmpi = "==5.0.8"
pip = "26.*"
hdf5 = { version = "*", build = "mpi_openmpi*" }
jupyterlab = "==4.5.0"
access-nri-intake = { version = "==1.6.0", channel = "accessnri" }
intake-esm-access = { version = "==2025.9.18", channel = "accessnri" }
ecgtools-access = { version = ">=2025.10.7", channel = "accessnri" }
access-py-telemetry = { version = "==0.1.10", channel = "accessnri" }
access-intake-utils = { version = "==0.1.7", channel = "accessnri" }
intake-dataframe-catalog = { version = "==0.5.1", channel = "conda-forge" }
yamanifest = { version = ">=0.3.12", channel = "accessnri" }
access-med-tools = { version = "==0.1.23", channel = "accessnri" }
access-moppy = { version = "==1.0.9b", channel = "accessnri" }
shumlib = { channel = "accessnri" }
aiohttp = "*"
aiohttp-cors = "*"
anytree = "*"
arch-py = "*"
argopy = "*"
arm_pyart = "*"
astropy = "*"
asyncssh = "*"
autopep8 = "*"
av = "*"
bargeparse = "*"
black = "*"
bokeh = "*"
bottleneck = "*"
branca = "*"
cartopy = "*"
cdo = ">2.3.0"
celluloid = "*"
cf-python = "*"
cf-units = "*"
cfchecker = "*"
cfgrib = "*"
cftime = "*"
cfunits = "*"
climpred = "*"
cmcrameri = "*"
cmdline_provenance = "*"
cmocean = "*"
cmor = "*"
compliance-checker = "*"
conda-build = "*"
conda-lock = "*"
conda-tree = "*"
crick = "*"
cupy = "*"
cvxpy = "*"
dask-jobqueue = "*"
dask-labextension = "*"
dask-ml = "*"
dask-xgboost = "*"
dataclasses-json = "*"
dataset = "*"
datashader = "*"
descartes = "*"
distributed = "*"
doc8 = "*"
docrep = "*"
dreqpy = "*"
earthpy = "*"
eccodes = "*"
ecmwf-api-client = "*"
eofs = "*"
erddapy = "*"
esmf = "*"
esmpy = "*"
esmvalcore = "2.14.*"
f90nml = "*"
ffmpeg = "*"
filelock = "*"
fiona = "*"
flox = "*"
folium = "*"
fortran-language-server = "*"
fs = "*"
gcc_linux-64 = "*"
gcm_filters = "*"
geocat-comp = "*"
geocat-viz = "*"
geoplot = "*"
geopy = "*"
gridfill = "*"
gsw = "*"
h5py = "*"
hdbscan = "*"
holoviews = "*"
httpx = "*"
hupper = "*"
hvplot = "*"
icclim = "*"
ilamb = "==2.7.2"
intake = "*"
ipdb = "*"
ipympl = "*"
ipynbname = "*"
ipywidgets = "*"
iris-grib = "*"
jags = "*"
jinja2 = "*"
joblib = "*"
jq = "*"
jsonschema = ">=4.18.1"
jupyter = "*"
jupyter-book = "*"
jupyter-resource-usage = "*"
jupyter-server-proxy = "*"
jupyterlab_server = "*"
kerchunk = "*"
lftp = "*"
libgdal = "*"
libtiff = "*"
line_profiler = "*"
lmfit = "*"
mamba = "*"
matchpy = "*"
matplotlib-scalebar = "*"
matplotlib-venn = "*"
mayavi = "*"
memory_profiler = "*"
metpy = "*"
mo_pack = "*"
moderngl = "*"
mpi4py = "*"
mpl-scatter-density = "*"
mplotutils = "*"
mplleaflet = "*"
mscorefonts = "*"
nbdime = "*"
nb_conda_kernels = "*"
nbval = "*"
nc-time-axis = "*"
ncdata = "*"
ncdu = "*"
nctoolkit = "*"
neutralocean = "*"
ninja = "*"
nodejs = "*"
notebook = "==7.5.0"
numba = "*"
numexpr = "*"
nvidia-ml-py = "*"
odc-geo = "*"
opencv = "*"
palettable = "*"
panel = "*"
papermill = "*"
param = "*"
parcels = "*"
pdbufr = "*"
pillow = "*"
pint = "*"
plotly = "*"
polars = "*"
poppler = "*"
posix_ipc = "*"
psutil = "*"
pyaml = "*"
pyarrow = "*"
pydantic = "*"
pydap = "*"
pyextremes = "*"
pygam = "*"
pygamma_n = "*"
pygrib = "*"
pygmt = "*"
pyhdf = "*"
pylint = "*"
pymannkendall = "*"
pysal = "*"
pyshp = "*"
pysteps = "*"
pytables = "*"
pytest = "*"
pytest-cov = "*"
pytest-subtests = "*"
python-eccodes = "*"
pytorch = { version= "*", channel = "pytorch"}
pytorch-cuda = {version = ">=12.4,<13", channel ="pytorch"}
python-graphviz = "*"
python-magic = "*"
python-stratify = "*"
quaternion = "*"
rasterio = "*"
rasterstats = "*"
rechunker = "*"
regionmask = "*"
rioxarray = "*"
ruff = "*"
s3fs = "*"
satpy = "*"
scores = "*"
seaborn = "*"
sh = "*"
shellcheck = "*"
siphon = "*"
spyder-kernels = "*"
sqlalchemy = "*"
statsmodels = "*"
sympy = "*"
tensorflow = "*"
timezonefinder = "*"
tintx = "*"
tqdm = "*"
twine = "*"
u8darts-all = "*"
ucx-py = { channel = "rapidsai" }
ucx = "==1.18.1"
ultraplot = "*"
ujson = "*"
uncertainties =">=3.2.3,!=3.2.4"
vtk = "*"
watchdog = "*"
watermark = "*"
wavespectra = "*"
webcolors = "*"
windspharm = "*"
wradlib = "*"
wrf-python = "*"
xarray-spatial = "*"
xarraymannkendall = "*"
xcdat = "*"
xclim = "*"
xesmf = "*"
xgcm = "*"
xhistogram = "*"
xmip = "*"
xmitgcm = "*"
xmovie = "*"
xrft = "*"
xskillscore = "*"
xwrf = "*"
esmvaltool = "2.14.*"
cdsapi = "*"
lime = "*"
mapgenerator = ">=1.0.5"
natsort = "*"
openpyxl = "*"
pys2index = "*"
python-cdo = "*"
seawater = "*"
flake8 = "*"
pytest-env = "*"
pytest-html = "*"
pytest-metadata = "*"
pytest-mock = "*"
pytest-xdist = "*"
autodocsumm = ">=0.2.2"
nbsphinx = "*"
pydata-sphinx-theme = "*"
codespell = "==2.3.0"
docformatter = "==1.7.5"
imagehash = "*"
isort = "==5.13.2"
pre-commit = "*"
prospector = ">=1.12"
pyroma = "*"
yamllint = "==1.35.1"
yapf = "*"
ncl = ">=6.6.2"
imagemagick = "*"
nco = "*"
r-base = ">=3.5"
r-abind = "*"
r-akima = "*"
"r-climdex.pcic" = "*"
r-climprojdiags = "*"
r-docopt = "*"
r-dotcall64 = "*"
r-functional = "*"
r-ggplot2 = "*"
r-gridextra = "*"
r-logging = "*"
r-mapproj = "*"
r-maps = "*"
r-multiapply = "*"
r-ncdf4 = "*"
"r-ncdf4.helpers" = "*"
r-pcict = "*"
r-plyr = "*"
r-rcolorbrewer = "*"
r-rcpp = "*"
r-s2dverification = "*"
r-snow = "*"
r-spei = "*"
r-udunits2 = "*"
r-yaml = "*"
r-git2r = "*"
r-lintr = "==3.1.2"
r-styler = "==1.10.3"
knem-headers = ">=1.1.4,<2"
virtualizarr = ">=2.4.0,<3"
icechunk = ">=1.1.21,<2"
python-swiftclient = ">=4.10.0,<5"
python-openstackclient = ">=9.0.0,<10"
parsl = ">=2026.3.16,<2027"

[pypi-dependencies]
lavavu = "==1.9.10"
lavavu-osmesa = "==1.9.10"
railroad-diagrams = "*"
accessvis = "==1.1.4"
py360convert = "*"
pycnv = ">=0.5.0"
cmip7-data-request-api = "*"
nci-ipynb = ">=2023.11.0.3, <2024"
