name: benchcab
channels:
- accessnri
- conda-forge
- nodefaults
dependencies:
# Note: the pinned benchcab version should match the BENCHCAB_VERSION
# environment variable in environments/benchcab/config.sh:
- accessnri::benchcab==4.3.0
- accessnri::payu>=1.1.7
