name: med-condaenv
channels:
- conda-forge
- accessnri
variables:
  CARTOPY_USER_BACKGROUNDS: /g/data/xp65/public/apps/cartopy-data/backgrounds
dependencies:
- apscheduler
- fs
- python>=3.9
- libnetcdf=*=mpi_openmpi* # pinned for solver stability
- pip
- pytest >=3.9,!=6.0.0rc1,!=6.0.0
- pytest-cov
- autopep8
- cartopy
- pyyaml
- cdo>=1.9.5 # pinned for solver stability
- matplotlib
- jinja2
- dask
- distributed
- dask-labextension
- panel
- hvplot
- datashader
- iris>=3.1.0
- iris-esmf-regrid
- iris-grib
- intake
- access-nri-intake>=0.1.1
- netcdf4<=1.6.0 ### Workaround for https://github.com/pydata/xarray/issues/7079
- mo_pack
- nodejs>=20.0.0
- numpy>=1.21, !=1.24.3, <=1.23.5  # severe masking bug
- pandas
- scipy
- h5py
- numba
- scikit-image
- jupyter
- notebook<6.5.3
- jupyter_nbextensions_configurator
- jupyter_contrib_nbextensions
- jupyterlab
- jsonschema>=4.18.1
- jupyterlab_server
- jupyter-server-proxy
- jupyter-resource-usage
- greenlet ### Dependency of... something?
- objgraph ### Unlisted dependency of greenlet
- asyncssh
- gevent
- openmpi==4.1.6
- mpi4py
- esmf=*=mpi_openmpi*
- esmpy
- pytest-json-report ### Needed for esmpy
- xesmf >=0.7.1
- xarray >=0.12.0
- shapely
- cf_xarray
- sparse
- coecms::ucx-py
- xgboost >1.6.1  # github.com/ESMValGroup/ESMValTool/issues/2779
- med-diagnostics==0.0.1 # pining for now
- cdms2
- access-med-tools
- pip:
  - railroad-diagrams ### Unlisted dependency of pip and pyparsing 
  - git+https://github.com/rubisco-sfa/ILAMB.git@v2.7.1

  
# Julia (dependencies installed by separate script)
- julia
