name: med-condaenv
channels:
- conda-forge
- accessnri
variables:
  CARTOPY_USER_BACKGROUNDS: /g/data/xp65/public/apps/cartopy-data/backgrounds
dependencies:
- python>=3.9
- openmpi
- mpi4py
- pip
- pytest >=3.9,!=6.0.0rc1,!=6.0.0
- libnetcdf=*=mpi_openmpi*
- pytest-cov
- autopep8
- ilamb 2.7.*
- access-nri-intake==0.0.9 # Keep pinned to latest version while in development
- esmvaltool 2.9.*
- jupyter
- notebook<7.0 # jupyter_contrib_nbextensions not compatible with version 7
- jupyter_contrib_nbextensions
- jupyterlab
- jupyterlab_server
- jupyter-server-proxy
- jupyter-resource-usage
- openmpi
- mpi4py
- med-diagnostics
- pyproj>=3.6.1
- coecms::ucx-py
- dask-labextension
- iris-grib # Can we do without?
- hvplot # Why do we need this?
- datashader # why do we need this?
- mo_pack # why do we need this?
- nodejs # why do we need this?
- h5py # why do we need this?
- greenlet # why do we need this?
- objgraph # unlisted dependency of greenlet
- asyncssh # why do we need this?
- pytest-json-report ## needed for esmpy
- pip:
  - railroad-diagrams ### Unlisted dependency of pip and pyparsing
  - access-med-utils==0.1.6
  
# Julia (dependencies installed by separate script)
- julia
