name: med-condaenv
channels:
  - conda-forge
  - accessnri
  - nodefaults
variables:
  CARTOPY_USER_BACKGROUNDS: /g/data/xp65/public/apps/cartopy-data/backgrounds
dependencies:
  - pip!=21.3
  - python>=3.8
  - access-nri-intake==0.0.8 # Keep pinned to latest version while in development
  - apscheduler
  - aiohttp
  - cartopy
  - cdo>=1.9.7
  - cdsapi
  - cf-units
  - cftime
  - cmocean
  - cython
  - dask
  - dask-labextension
  - datashader
  - ecmwf-api-client
  - eofs
  - esmpy
  - esmvalcore 2.8.*
  - fiona
  - fire
  - fs
  - gdal
  - h5py
  - hvplot
  - ilamb
  - intake
  - iris>=3.1.0
  - iris-esmf-regrid
  - jinja2
  - joblib
  - lime
  - mapgenerator>=1.0.5
  - matplotlib-base # pinning matplotlib to 3.5.3 temporarily until plotnine issue is fixed https://github.com/has2k1/plotnine/issues/620
  - matplotlib==3.5.3  #
  - natsort
  - nc-time-axis
  - netCDF4
  - numba
  - numpy>=1.21
  - nodejs
  - packaging
  - openpyxl
  - pandas
  - panel
  - progressbar2
  - prov
  - psyplot
  - psy-maps
  - psy-reg
  - psy-simple
  - pydantic<2.0 # Until https://github.com/intake/intake-esm/pull/619 is fixed
  - pyproj>=2.1
  - python-cdo
  - python-dateutil
  - pyyaml
  - rasterio
  - requests
  - ruamel.yaml
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - seawater
  - shapely <2.0.0  # github.com/ESMValGroup/ESMValTool/issues/2965
  - xarray>=0.12.0
  - xesmf==0.3.0
  - xgboost>1.6.1  # github.com/ESMValGroup/ESMValTool/issues/2779
  - xlsxwriter
  - zarr
  # Python packages needed for testing
  - flake8
  - autopep8
  - pytest >=3.9,!=6.0.0rc1,!=6.0.0
  - pytest-cov
  - pytest-env
  - pytest-html !=2.1.0
  - pytest-metadata >=1.5.1
  - pytest-mock
  - pytest-xdist
  # Python packages needed for building docs
  - autodocsumm>=0.2.2
  - nbsphinx
  - sphinx>=6.1.3
  - sphinx_rtd_theme
  # Python packages needed for development
  - codespell
  - docformatter
  - isort
  - pre-commit
  - prospector
  - pyroma
  # - vprof not on conda-forge
  - yamllint
  - yapf
  - jupyter
  - jupyterlab=3.6.4
  - jupyterlab_server
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - jupyter-server-proxy
  - jupyter-book
  - jupyter-resource-usage
  - greenlet ### Dependency of... something?
  - objgraph ### Unlisted dependency of greenlet
  - asyncssh
  - gevent

  # NCL and dependencies
  - ncl
  - cdo
  - imagemagick
  - nco

  # R and dependencies
  - cdo
  - r-base >=3.5
  - r-abind
  - r-akima <=0.6-2.3  # see https://github.com/ESMValGroup/ESMValTool/issues/2695
  - r-climdex.pcic
  - r-climprojdiags
  - r-docopt
  - r-dotcall64
  - r-functional
  - r-ggplot2
  - r-gridextra
  - r-lintr
  - r-logging
  - r-mapproj
  - r-maps
  - r-multiapply
  - r-ncdf4
  - r-ncdf4.helpers
  - r-pcict
  - r-plyr
  - r-rcolorbrewer
  - r-rcpp
  - r-s2dverification
  - r-snow
  - r-spei
  - r-styler
  - r-udunits2
  - r-yaml
  # R packages needed for development
  - r-git2r  # dependency of lintr
  - r-lintr
  - r-styler

  # Julia (dependencies installed by separate script)
  - julia

- pip:
  - railroad-diagrams ### Unlisted dependency of pip and pyparsing

