name: med-condaenv
channels:
- conda-forge
variables:
  CARTOPY_USER_BACKGROUNDS: /g/data/xp65/public/apps/cartopy-data/backgrounds
dependencies:
- python>=3.10
- apscheduler
- fs
- libnetcdf>=4.7.4=mpi_openmpi* # pinned for solver stability
- pip
- pytest
- pytest-cov
- autopep8
- cartopy
- pyyaml
- cdo>=1.9.5 # pinned for solver stability
- matplotlib
- jinja2
- ilamb 2.7.*
- dask
- distributed
- dask-labextension
- panel
- hvplot
- datashader
- iris
- iris-grib
- intake
- netcdf4<=1.6.0 ### Workaround for https://github.com/pydata/xarray/issues/7079
- mo_pack
- nodejs
- numpy>=1.21
- pandas
- scipy
- h5py
- pyproj>=3.6.1
- numba
- esmvaltool 2.9.*
- esmvaltool-python
- esmvaltool-ncl
- scikit-image
- jupyter
- notebook
- jupyter_nbextensions_configurator
- jupyter_contrib_nbextensions
- jupyterlab
- jupyterlab_server
- jupyter-server-proxy
- jupyter-resource-usage
- greenlet ### Dependency of... something?
- objgraph ### Unlisted dependency of greenlet
- asyncssh
- gevent
- openmpi
- mpi4py
- esmf>=8.0.1,<8.4.2=mpi_openmpi*
- esmpy>=8.0.1=mpi_openmpi*
- xesmf
- xarray
- shapely
- cf_xarray
- sparse
- coecms::ucx-py
- accessnri::access-nri-intake
- accessnri::med-diagnostics
- pip:
  - railroad-diagrams ### Unlisted dependency of pip and pyparsing
  - access-med-utils
  
# Julia (dependencies installed by separate script)
#- julia
