name: med-condaenv
channels:
- conda-forge
- accessnri
variables:
  CARTOPY_USER_BACKGROUNDS: /g/data/xp65/public/apps/cartopy-data/backgrounds
dependencies:
- apscheduler
- fs
- python>=3.9
- pip!=21.3
- pytest >=3.9,!=6.0.0rc1,!=6.0.0
- pytest-cov
- autopep8
- pyyaml
- cdo>=1.9.5 # pinned for solver stability
# pinning matplotlib to 3.5.3 temporarily until plotnine issue is fixed https://github.com/has2k1/plotnine/issues/620
- matplotlib==3.5.3  #
- jinja2
- ilamb
- dask
- dask-labextension
- panel
- hvplot
- datashader
- iris>=3.1.0
- iris-esmf-regrid
- intake
- access-nri-intake==0.0.8 # Keep pinned to latest version while in development
# - intake-esm<2023.7.7 # Can remove with access-nri-intake==0.0.9
# - ecgtools<2023.7.13 # Can remove with access-nri-intake==0.0.9
- pydantic<2.0 # Can remove with access-nri-intake==0.0.9
- netcdf4<=1.6.0 ### Workaround for https://github.com/pydata/xarray/issues/7079
- nodejs
- numpy>=1.21, !=1.24.3  # severe masking bug
- pandas
- scipy
- h5py
- numba
- esmvaltool 2.9.*
- esmvaltool-python
- esmvaltool-ncl
- scikit-image
- jupyter
- jupyterlab=3.6.4
- jupyterlab_server
- jupyter_nbextensions_configurator
- jupyter_contrib_nbextensions
- jupyter-server-proxy
- jupyter-book
- jupyter-resource-usage
# - jsonschema>=4.18.1
- greenlet ### Dependency of... something?
- objgraph ### Unlisted dependency of greenlet
- asyncssh
- gevent
- openmpi
- mpi4py
- esmf
- esmpy
- xesmf >=0.7.1
- xarray >=0.12.0
- shapely
- cf_xarray
- sparse
- xgboost >1.6.1  # github.com/ESMValGroup/ESMValTool/issues/2779
- pip:
  - railroad-diagrams ### Unlisted dependency of pip and pyparsing
  
# Julia (dependencies installed by separate script)
- julia
