name: med-condaenv
channels:
- conda-forge
- accessnri
variables:
  CARTOPY_USER_BACKGROUNDS: /g/data/xp65/public/apps/cartopy-data/backgrounds
dependencies:
- apscheduler
- fs
- python>=3.9
- pip
- pytest
- pytest-cov
- autopep8
- pyyaml
- cdo>=1.9.5 # pinned for solver stability
# pinning matplotlib to 3.5.3 temporarily until plotnine issue is fixed https://github.com/has2k1/plotnine/issues/620
- matplotlib==3.5.3  #
- pydantic<2.0 # Until https://github.com/intake/intake-esm/pull/619 is fixed
- jinja2
- ilamb
- dask
- dask-labextension
- panel
- hvplot
- datashader
- iris>=3.1.0
- iris-esmf-regrid
- intake
- access-nri-intake==0.0.8 # Keep pinned to latest version while in development
- netcdf4<=1.6.0 ### Workaround for https://github.com/pydata/xarray/issues/7079
- nodejs
- numpy>=1.21 # Mule dependency
- pandas
- scipy
- h5py
- numba
- esmvaltool>=2.8,<2.9 # Pin esmvaltool version to 2.8
- esmvaltool-python
- esmvaltool-ncl
- scikit-image
- jupyter
- jupyterlab=3.6.4
- jupyterlab_server
- jupyter_nbextensions_configurator
- jupyter_contrib_nbextensions
- jupyter-server-proxy
- jupyter-book
- jupyter-resource-usage
- greenlet ### Dependency of... something?
- objgraph ### Unlisted dependency of greenlet
- asyncssh
- gevent
- julia
- openmpi
- mpi4py
- esmf
- esmpy
- xesmf==0.3.0
- xarray
- shapely
- cf_xarray
- sparse
- pip:
  - railroad-diagrams ### Unlisted dependency of pip and pyparsing

