name: analysis3-edge
channels:
- conda-forge
- nodefaults
dependencies:
# SPEC0 packages
- python==3.11.*
- dask==2025.9.*
- numpy>=2.0
- scipy==1.15.*
- matplotlib>3.9
- pandas==2.3.*
- scikit-image==0.25.*
- scikit-learn==1.7.*
- xarray==2025.9.*
- ipython<9.0
- zarr>3.0
- iris==3.12.*
- netcdf4==1.7.*
- libnetcdf=*=mpi_openmpi*
- openmpi==5.0.5
- pip=25.*
- hdf5=1.14.*=mpi_openmpi*
- jupyterlab==4.4.*
- cmor==3.9.*
- accessnri::access-nri-intake==1.2.*
- accessnri::access-py-telemetry==0.1.*
- numba
- dask-ml
- datashader
- geocat-comp
- icclim
- neutralocean
#- regional-mom6 needs numpy <2
#- tensorflow
- u8darts-all
#- wavespectra, needs numpy <2
#- wrf-python needs numpy <2
- xarray-spatial
- aiohttp
- aiohttp-cors
- anytree
- arch-py
- argopy
- arm_pyart
- asyncssh
- autopep8
- bargeparse
- black
- bokeh
- bottleneck
- branca
- cartopy
- cdo
- celluloid
- cf-python>=3.17
- cf-units
- cfgrib
- cftime
- cfunits
- climpred
- cmdline_provenance
- cmocean
- cmor
- compliance-checker
- conda-build
- conda-lock
- conda-tree
- conda-verify
- crick
- cupy
- cvxpy
- dask-jobqueue
- dask-labextension
- dask-xgboost
- dataclasses-json
- dataset
- descartes
- distributed
- doc8
- docrep
- dreqpy
- earthpy
- eccodes
- ecmwf-api-client
- eofs
- erddapy
- esmf
- esmpy
- f90nml
- ffmpeg
- filelock
- fiona
- flox
- folium
- fortran-language-server
- fs
- gcc_linux-64
- gcm_filters
- geocat-viz
- geoplot
- geopy
- gridfill
- gsw
- h5py
- hdbscan
- holoviews
- httpx
- hupper
- hvplot
- intake
- intake-esm>=2025.7.9
- ipdb
- ipympl
- ipynbname
- ipywidgets
- iris-grib
- jags
- joblib
- jq
- jupyter
- jupyter-book
- jupyter-resource-usage
- jupyter-server-proxy
- jupyterlab_server
- kerchunk
- lftp
- libgdal
- libtiff
- line_profiler
- lmfit
- mamba
- matchpy
- matplotlib-scalebar
- matplotlib-venn
- mayavi
- memory_profiler
- metpy
- mo_pack
- mpl-scatter-density
- mplleaflet
- mscorefonts
- nb_conda_kernels
- nbdime
- nc-time-axis
- ncdu
- nctoolkit
- ninja
- nodejs
- notebook
- numexpr
- odc-geo
- opencv
- panel
- param
- parcels
- pdbufr
- pint
- plotly
- poppler
- posix_ipc
- psutil
- pydantic
- pydap
- pyextremes
- pygam
- pygrib
- pyhdf
- pylint
- pymannkendall
- pysal
- pytables
- pytest
- pytest-cov
- python-eccodes
- python-graphviz
- python-magic
- python-stratify
- pytorch-gpu
- rasterio
- rasterstats
- rechunker
- regionmask
- rioxarray
- ruff
- s3fs
- satpy
- seaborn
- sh
- sharppy
- shellcheck
- siphon
- spyder-kernels
- sqlalchemy
- statsmodels
- sympy
- timezonefinder
- tintx
- tqdm
- twine
- ujson
- vtk
- watchdog
- watermark
- webcolors
- windspharm
- wradlib
- xarraymannkendall
- xcdat
- xclim
- xesmf
- xgcm
- xhistogram
- xmip
- xmitgcm
- xmovie
- xrft
- xskillscore
- xwrf
