name: Pixi Broken Package Check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'environments/analysis3/pixi.toml'
      - 'environments/analysis3/pixi.lock'

permissions:
  contents: read
  pull-requests: write

jobs:
  pixi-broken-package-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/workflows/pixi-broken-package-check.yml
            environments/analysis3/pixi.toml
            environments/analysis3/pixi.lock
            scripts/check_broken_packages.py
          sparse-checkout-cone-mode: false

      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 #v0.9.6
        with:
          run-install: false

      - name: Generate broken package report
        working-directory: ./environments/analysis3
        run: pixi run --as-is check-broken-packages

      - name: Comment broken package report on PR
        if: always()
        uses: access-nri/actions/.github/actions/comment@main
        with:
          number: ${{ github.event.pull_request.number }}
          label: pixi-broken-package-check
          message-file: /tmp/broken-packages.md
