name: Renovate (Conda)

on:
  schedule:
    - cron: "11 */2 * * *"   # run every 2 hours
  workflow_dispatch:

permissions:
  contents: write        # needed for committing branch updates
  pull-requests: write   # needed for creating/updating PRs
  issues: write          # optional: for PR comments/status

concurrency:
  group: renovate-conda
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      # Fine-grained PAT with access to this repo and permissions: Contents:RW, Pull requests:RW
      RENOVATE_TOKEN: ${{ secrets.GH_ANALYSIS3_DEPLOY }}
      # Optional: better timestamps for PR titles/changelogs
      TZ: Australia/Brisbane
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.7
        with:
          # Uses the config file in this repo
          configurationFile: .github/renovate.json
          # Optional: increase logging during setup
          # logLevel: info
